plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.181'
    id 'net.darkhax.curseforgegradle' version '1.1.15'
    id "com.modrinth.minotaur" version "2.+"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version =minecraft_version + "-" + mod_version + "-" + tag_platform
group = mod_group_id

base {
    archivesName = mod_name 
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name "Modmaven"
        url "https://modmaven.dev/"
    }
    maven {
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
}


dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'


    runtimeOnly "mezz.jei:jei-1.21.1-neoforge:${jei_version}"
    implementation "mezz.jei:jei-1.21.1-neoforge:${jei_version}"

    //AE2 
    compileOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    runtimeOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    implementation "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    implementation "org.appliedenergistics:guideme:${guideme_version}"
    }

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            issue_tracker          : issue_tracker,
            ae2_version             : ae2_version,
            jei_version             : jei_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {

    apiToken = System.getenv("CURSE_API_KEY")

    // The main file to upload
    def mainFile = upload(559313, jar)
    mainFile.releaseType = 'release'
    mainFile.changelog = 'A changelog can be found at https://github.com/Hexeption/AEInfinityBooster'
    mainFile.changelogType = 'markdown'
    mainFile.gameVersions = ['1.21.1']
    mainFile.addModLoader("neoforge")
    mainFile.displayName = "AEInfinityBooster ${version}"


}

modrinth {
   token = System.getenv("MODRINTH_API_KEY")
    projectId = 'VQhDBNs8'
    versionName = "AEInfinityBooster $version"
    changelog = 'A changelog can be found at https://github.com/Hexeption/AEInfinityBooster'
    uploadFile = jar
    gameVersions = ["1.21.1"]
    loaders = ["neoforge"]
    dependencies {
        required.version "ae2", "19.1.2-beta"
    }
}
