org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]

neo_version=26.1.2.64-beta

loader_version_range=[4,)

## Mod Properties
mod_id=aeinfinitybooster
mod_name=AEInfinityBooster
mod_license=GNU Lesser General Public License
mod_version=1.0.0
mod_group_id=uk.co.hexeption.aeinfinitybooster
mod_authors=Hexeption
mod_description=Adds Infinite Range Card and Dimension Card to AE2
