org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.warning.mode=none

## Parchment Properties
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17



## NeoForge Properties
neo_version=21.1.215
loader_version_range=[4,)

## Mod Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
tag_platform=NeoForge
mod_id=aeinfinitybooster
mod_name=AEInfinityBooster
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=uk.co.hexeption.aeinfinitybooster
mod_authors=Hexeption
mod_description=Adds Infinite Range Card and Dimension Card to AE2
issue_tracker=https://github.com/Hexeption/AEInfinityBooster/issues

## Applied Energistics 2 Properties
ae2_version=19.2.17
guideme_version=21.1.15

## JEI Properties
jei_version=19.27.0.340