org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.122
neo_version_range=[21.1.122,)

loader_version_range=[4,)

## Mod Properties
mod_id=aeinfinitybooster
mod_name=AEInfinityBooster
mod_license=GNU Lesser General Public License
mod_version=1.0.0
mod_group_id=uk.co.hexeption.aeinfinitybooster
mod_authors=Hexeption
mod_description=Adds Infinite Range Card and Dimension Card to AE2
